services:
  api:
    build: .
    command: ./wait-for-db.sh api-db python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    depends_on:
      - api-db
    env_file:
      - .env
    networks:
      - kong-net
  api-db:
    image: mariadb:11.4
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - api-db-data:/var/lib/mysql
    networks:
      - kong-net
  api-tests:
    build: .
    command: ["sh", "-c", "./wait-for-db.sh api-db && pytest"]
    volumes:
      - .:/app
    depends_on:
      - api-db
    env_file:
      - .env
    networks:
      - kong-net

volumes:
  api-db-data:

networks:
  kong-net:
    name: kong-net
    driver: bridge
    
